# Generated by Django 4.0.1 on 2022-02-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_dayname_plan_alter_recipe_id_recipeplan_plan_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeplan',
            name='day_name',
        ),
        migrations.AddField(
            model_name='recipeplan',
            name='day_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jedzonko.dayname'),
            preserve_default=False,
        ),
    ]
