# Generated by Django 4.0.1 on 2022-02-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0005_recipe_how_to_prepare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='how_to_prepare',
        ),
    ]
