# Generated by Django 4.0.1 on 2022-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_remove_recipe_how_to_prepare'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='how_to_prepare',
            field=models.TextField(null=True),
        ),
    ]
