# Generated by Django 4.0.1 on 2022-02-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_recipe_how_to_prepare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='order',
            field=models.IntegerField(),
        ),
    ]
